
const TeluguMoviesData = [
  {
    id: 1,
    name: 'Nirvana',
    thumbnail: 'https://drive.google.com/uc?id=1jEqN6j6uqaTY6Ta4SxSLLGQfXoNr1LWS',
    link: 'https://www.youtube.com/watch?v=3VmTENzmqZM&t?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
  },
  {
    id: 2,
    name: 'Tholi Prema',
    thumbnail: 'https://i.pinimg.com/736x/67/9d/4e/679d4ef0ec2bb195ed704a2e3f6d2ca3.jpg',
    link: 'https://www.youtube.com/watch?v=uoGCXFuDiQo?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 3,
    name: 'Hit',
    thumbnail: 'https://drive.google.com/uc?id=11hJZXcnslTNaJZmDzlXyrmnFMpFZf8qh',
    link: 'https://www.youtube.com/watch?v=YqX0jaXDABM?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 4,
    name: 'Eega',
    thumbnail: 'https://drive.google.com/uc?id=11oyKMLVXS4a0FIQRRLYHJxQAxV_RegDH',
    link: 'https://www.youtube.com/watch?v=9q2aLB98gSk?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 5,
    name: 'Miss Shetty Mr Polishetty',
    thumbnail: 'https://drive.google.com/uc?id=1SRAMMaKU9H3ZBBauP6ljWjqK5U2PCgR2',
    link: 'https://www.youtube.com/watch?v=2yuGHIaALVw?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 6,
    name: 'Ante Sundaraniki',
    thumbnail: 'https://drive.google.com/uc?id=1CzKuJHwdJJaO3LQ9c1VWoMjzMiVRDkeb',
    link: 'https://www.youtube.com/watch?v=pOmPTwA3fsU?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 7,
    name: 'Rangasthalam',
    thumbnail: 'https://drive.google.com/uc?id=1cyHKyksEEBLStbwaumLK_SpU-9ITePVy',
    link: 'https://www.youtube.com/watch?v=GWWHI7SE0KQ?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 8,
    name: 'Vedam',
    thumbnail: 'https://drive.google.com/uc?id=1pFqzeCOnUP-4KWGtSmyJytKxMOXvR9Om',
    link: 'https://www.youtube.com/watch?v=N8Zm4iuw2co?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 9,
    name: 'Custody',
    thumbnail: 'https://drive.google.com/uc?id=1iWHTiOO91zV6I98oNLv6hzkq1t8w2Icy',
    link: 'https://www.youtube.com/watch?v=jMMaZXXfwjI?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
  {
    id: 10,
    name: 'Oopiri',
    thumbnail: 'https://drive.google.com/uc?id=1IpjwI9ospwhFmpJfRER5x_dE0P3gF9v1',
    link: 'https://www.youtube.com/watch?v=L7wLBcBzCQ4?rel=0',
    director: 'Director Name',
    gener: 'genre',
    rating: 4.5,
    description: 'Description of Nirvana movie.',
    actors: ['Actor 1', 'Actor 2'],
    producer: 'Producer Name',
    year: 2023,
    writer: 'Writer Name',
    language: 'Telugu',
  },
];



export { TeluguMoviesData };
